# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * 1,3,5'
    - cron: '30 5 * * 2,4'


jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore ./api.engine-v2.sln
      - name: .NET Build (Not on Monday or Wednesday)
        if: github.event.schedule != '30 5 * * 1,3,5'
        run: dotnet build --no-restore ./api.engine-v2.sln
      - name: .NET Test
        run: dotnet test --no-build --verbosity normal ./api.engine-v2.sln
        
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      github.event.state == 'error' ||
      github.event.state == 'failure'
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION